#!/bin/bash

# this tool requires GNU Mtools, GNU coreutils, dd, and cat.

if [ ! -f file.bin ]; then
    dd if=/dev/urandom of=file.bin bs=1024 count=1
fi
FILE_BIN_MD5=$(md5sum file.bin | cut -d' ' -f1)
touch -d 2024-02-2019:18:00 file.bin

if [ ! -f longfilename.bin ]; then
    dd if=/dev/urandom of=longfilename.bin bs=1024 count=1
fi
LONGFILENAME_BIN_MD5=$(md5sum longfilename.bin | cut -d' ' -f1)
touch -d 2024-02-2019:18:00 longfilename.bin

if [ ! -f 유니코드.bin ]; then
    dd if=/dev/urandom of=유니코드.bin bs=1024 count=1
fi
UTEST1_BIN_MD5=$(md5sum 유니코드.bin | cut -d' ' -f1)
touch -d 2024-02-2019:18:00 유니코드.bin

dd if=/dev/zero of=fat12.img bs=1048576 count=1
dd if=/dev/zero of=fat16.img bs=1048576 count=16
dd if=/dev/zero of=fat32.img bs=1048576 count=64

mformat -i fat12.img -v "FAT Filesystem Test"
mformat -i fat16.img -v "FAT Filesystem Test"
mformat -F -i fat32.img -v "FAT Filesystem Test"

mcopy -i fat12.img -p -m -- file.bin ::
mcopy -i fat12.img -p -m -- longfilename.bin ::
mcopy -i fat12.img -p -m -- 유니코드.bin ::
mmd -i fat12.img ::/directory1
mcopy -i fat12.img -p -m -- file.bin ::/directory1
mmd -i fat12.img ::/directory2
mcopy -i fat12.img -p -m -- longfilename.bin ::/directory2

cat > fat12-tree.txt <<EOF
# directory tree of fat12.img
# file_name file_size date_created time_created md5_checksum

FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
유니코드.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
directory1 dir
directory2 dir

$ directory1
. dir
.. dir
FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ directory2
. dir
.. dir
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF
cat > fat12cl-tree.txt <<EOF
# directory tree of fat12.img
# case_sensitive = 1
# sfn_lowercase = 1
# unicode_enabled = 0
# file_name file_size date_created time_created md5_checksum

file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
????.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
directory1 dir
directory2 dir

$ directory1
. dir
.. dir
file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ directory2
. dir
.. dir
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF
cat > fat12clu-tree.txt <<EOF
# directory tree of fat12.img
# case_sensitive = 1
# sfn_lowercase = 1
# file_name file_size date_created time_created md5_checksum

file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
유니코드.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
directory1 dir
directory2 dir

$ directory1
. dir
.. dir
file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ directory2
. dir
.. dir
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF
cat > fat12csl-tree.txt <<EOF
# directory tree of fat12.img
# case_sensitive = 1
# lfn_enabled = 0
# sfn_lowercase = 1
# file_name file_size date_created time_created md5_checksum

file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfi~1.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
~1.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
direct~1 dir
direct~2 dir

$ direct~1
. dir
.. dir
file.bin 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ direct~2
. dir
.. dir
longfi~1.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF

mcopy -i fat16.img -p -m -- file.bin ::
mcopy -i fat16.img -p -m -- longfilename.bin ::
mcopy -i fat16.img -p -m -- 유니코드.bin ::
mmd -i fat16.img ::/directory1
mcopy -i fat16.img -p -m -- file.bin ::/directory1
mmd -i fat16.img ::/directory2
mcopy -i fat16.img -p -m -- longfilename.bin ::/directory2

cat > fat16-tree.txt <<EOF
# directory tree of fat16.img
# file_name file_size date_created time_created md5_checksum

FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
유니코드.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
directory1 dir
directory2 dir

$ directory1
. dir
.. dir
FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ directory2
. dir
.. dir
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF

mcopy -i fat32.img -p -m -- file.bin ::
mcopy -i fat32.img -p -m -- longfilename.bin ::
mcopy -i fat32.img -p -m -- 유니코드.bin ::
mmd -i fat32.img ::/directory1
mcopy -i fat32.img -p -m -- file.bin ::/directory1
mmd -i fat32.img ::/directory2
mcopy -i fat32.img -p -m -- longfilename.bin ::/directory2

cat > fat32-tree.txt <<EOF
# directory tree of fat32.img
# file_name file_size date_created time_created md5_checksum

FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
유니코드.bin 1024 2024-02-20 19:18 $UTEST1_BIN_MD5
directory1 dir
directory2 dir

$ directory1
. dir
.. dir
FILE.BIN 1024 2024-02-20 19:18 $FILE_BIN_MD5

$ directory2
. dir
.. dir
longfilename.bin 1024 2024-02-20 19:18 $LONGFILENAME_BIN_MD5
EOF
